#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

./node_modules/.pnpm/@craigmiller160+js-config@1.0.19_@testing-library+dom@9.3.4_@types+node@20.11.5_cross-env@7.0_plkqas5yoqpcdh5r272dkfgq4q/node_modules/lint-staged/bin/lint-staged.js --config ./node_modules/@craigmiller160/js-config/configs/lintstaged/.lintstagedrc